In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
X = iris.data[:, 2:]
y = iris.target

tree_clf = DecisionTreeClassifier(max_depth=None)
tree_clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [6]:
from sklearn.tree import export_graphviz

export_graphviz(
    tree_clf,
    out_file="iris_tree.dot",
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

In [9]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=10000, noise=0.4)
X, y

(array([[-0.32410074,  1.39961886],
        [-1.04841542,  1.00956918],
        [ 0.2771063 ,  0.67035117],
        ...,
        [ 1.10259615, -0.60227622],
        [ 1.21654492,  0.00996097],
        [-0.56076319,  0.47579495]]), array([0, 0, 0, ..., 1, 1, 0]))

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

tree_clf = DecisionTreeClassifier()
param_dict = {
    "max_leaf_nodes": [None, 2, 3, 4, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
}
clf = GridSearchCV(tree_clf, param_dict)
clf.fit(X_train, y_train)
clf.best_params_

{'max_leaf_nodes': 4}

In [19]:
from sklearn.metrics import accuracy_score

pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0.8584

In [22]:
from sklearn.model_selection import ShuffleSplit

classifiers = []
i = 0
for train_index, _ in ShuffleSplit(n_splits=1000, train_size=0.01).split(X_train):
    classifiers.append(
        DecisionTreeClassifier(max_leaf_nodes=4).fit(X_train[train_index,:], y_train[train_index])
    )

In [34]:
from scipy.stats import mode

pred = []

i = 0
for test_instance in X_test:
    test_instance = test_instance.reshape(1, -1)
    if (i % 30) == 0:
        print("predicting sample #" + str(i) + "/" + str(len(X_test)))
    clf_pred = []
    for clf in classifiers:
        clf_pred.append(clf.predict(test_instance))
    md, _ = mode(clf_pred)
    pred.append(md)
    i = i + 1
pred

predicting sample #0/2500
predicting sample #30/2500
predicting sample #60/2500
predicting sample #90/2500
predicting sample #120/2500
predicting sample #150/2500
predicting sample #180/2500
predicting sample #210/2500
predicting sample #240/2500
predicting sample #270/2500
predicting sample #300/2500
predicting sample #330/2500
predicting sample #360/2500
predicting sample #390/2500
predicting sample #420/2500
predicting sample #450/2500
predicting sample #480/2500
predicting sample #510/2500
predicting sample #540/2500
predicting sample #570/2500
predicting sample #600/2500
predicting sample #630/2500
predicting sample #660/2500
predicting sample #690/2500
predicting sample #720/2500
predicting sample #750/2500
predicting sample #780/2500
predicting sample #810/2500
predicting sample #840/2500
predicting sample #870/2500
predicting sample #900/2500
predicting sample #930/2500
predicting sample #960/2500
predicting sample #990/2500
predicting sample #1020/2500
predicting sample #1050/

[array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[1]]),
 array([[0]]),
 array([[0]]),
 array([[0]]),
 array([[1]]),
 array([[0

In [38]:
import numpy as np
accuracy_score(y_test, np.squeeze(pred))

0.862